-- table for sequence values
--CREATE TABLE INTERNAL_IDS (NEXT_ID IDENTITY);

-- tables
--Person(FNAME, LNAME, hourlyRate)

CREATE TABLE Person(ID IDENTITY, FNAME VARCHAR(200),LNAME VARCHAR(200),hourlyRate DOUBLE);

CREATE TABLE HelloWorld(ID IDENTITY, language VARCHAR(200), message VARCHAR(200), transdate DATE, translator_id INTEGER NOT NULL, CONSTRAINT FK1 FOREIGN KEY (translator_id) REFERENCES Person(ID))

--CREATE TABLE HelloWorld(ID IDENTITY, language VARCHAR(200), message VARCHAR(200), transdate DATE, translator_id INTEGER NOT NULL)
--INSERT INTO Person VALUES(100,'John','Smith',45.00);
--INSERT INTO Person VALUES(200,'Carlos','Perez',40.00);
--INSERT INTO Person VALUES(300,'Pierre','LeClair',40.00);

--INSERT INTO HelloWorld VALUES(1,'English','Hello World!','2008-10-10',100);
--INSERT INTO HelloWorld VALUES(2,'Spanish','Hola Mundo!','2008-10-10',200);
--INSERT INTO HelloWorld VALUES(3,'French','Bonjour Monde!','2008-10-10',300);

--CREATE TABLE Person(ID BIGINT NOT NULL PRIMARY KEY, FNAME VARCHAR(200),LNAME VARCHAR(200),hourlyRate DOUBLE);
--CREATE TABLE USER_ROLE (ID BIGINT NOT NULL PRIMARY KEY, TYPE_ID BIGINT NOT NULL, NAME VARCHAR(200), IS_COLMS TINYINT NOT NULL, IS_ACTIVE TINYINT NOT NULL, CONSTRAINT FK1 FOREIGN KEY (TYPE_ID) REFERENCES ROLE_TYPE(ID));

-- sets the first sequence value to 1000
--ALTER TABLE INTERNAL_IDS ALTER NEXT_ID RESTART WITH 1000;